### ISSUE TITLE
OMDb API is going private

### ISSUE THREAD

**Issue by natorojr** [gSchool/wd-ajax-hero#3]
The OMDb API is going private.

![screen shot 2017-05-12 at 1 53 12 pm](https://cloud.githubusercontent.com/assets/1237186/26016548/5f68108e-371a-11e7-8af3-e8692fd05a67.png)

You can read more here: https://www.patreon.com/posts/api-is-going-10743518

That would make this exercise potentially at risk, in the sense that students may not be able to complete it should the endpoint require a paid-for API key.

It's only $1, but having to pull out a credit card is obviously cumbersome and not ideal.

Should Galvanize purchase a key and share it with students? Or do we sunset this exercise?

@teb311 @joshwyatt

**Comment by lizTheDeveloper** [comment]
c5a8df09 <3 
Don't abuse it!
